### ISSUE TITLE
Date Field Format

### ISSUE THREAD

**Issue by dbarasa1** [BCCHR-IT/custom-template-engine#42]
Thanks for the great template.
We are trying to implement it for custom reporting.
It's pulling our datapoints in nicely however, we have runnn into a problem with the Dates Field.
The template converts our mm-dd-yyyy into yyyy-mm-dd.
What is the solution to this?
Durrant

**Comment by BCCHR-IT** [comment]
Hello @dbarasa1 , this is Dan Evans, the programming team lead here at BCCHR.

Dates are stored internally in REDCap in a single format, which converts to display based on how you have formatted the date in the Designer. When the CTE receives the information to populate the template, it is unaware of how you have requested the date be formatted in the Designer, so it defaults to the default format for dates the version of PHP you are using has stored. I have not yet thought of a way to retrieve the date format from REDCap to try "inheriting" the date format in the Custom Template Engine.

I can add this as a request for future development, though I'm not currently certain how to go about fixing it. If you have control over the web server that runs the PHP used by your REDCap server, one  thing you could try doing would be to change the default date format in you php.ini file:

https://www.php.net/manual/en/ibase.configuration.php

Beware! This will affect everything that PHP installation does, and I don't even know if it would fix your issue; it's just a thing that occurred to me to try which may solve more than this one issue for you.

**Comment by Seaborg** [comment]
Hi @dbarasa1, I faced the same issue so I used the smarty feature: "|date_format"
https://www.smarty.net/docsv2/en/language.modifier.date.format.tpl
In order to make it work with the plugin you need to change Template.php a tad.

For Module Version 3.2.1
1. 
Add this bold lines after around line 478:
With:
  case "if":
  **case "|date_format:'%d-%m-%Y'":
      break;**
  case "elseif":

2.
Replace below line around line 684:
&& !in_array($next_part, $this->logical_operators))
with:
&& !in_array($next_part, $this->logical_operators)
&& $next_part !== "|date_format:''")

Once above is changed you can format date in your template, e.g.
{$redcap['date_dx_dmy']|date_format:'%d-%m-%Y'}

**Comment by BCCHR-IT** [comment]
Hello @dbarasa1 ,

Thanks to the work of @Seaborg above, I have implemented some very basic date formatting with formatting strings in Smarty. They will be in the next release of v4, which will likely be called v4.1. No date for release yet, but it's in the dev branch of the code base at the moment! I will also look into changing the module settings to allow for a global default date format, as well as implementing more formatting options.

Thank you again @Seaborg !
